/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import HTTPValidationError from './model/HTTPValidationError';
import LocationInner from './model/LocationInner';
import Token from './model/Token';
import User from './model/User';
import ValidationError from './model/ValidationError';
import AccountApi from './api/AccountApi';
import AllApi from './api/AllApi';
import ArtikalApi from './api/ArtikalApi';
import ArtikalCenaApi from './api/ArtikalCenaApi';
import ArtikalRacunApi from './api/ArtikalRacunApi';
import BackupApi from './api/BackupApi';
import FirmaApi from './api/FirmaApi';
import ProdavnicaApi from './api/ProdavnicaApi';
import RacunApi from './api/RacunApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FastApi = require('index'); // See note below*.
* var xxxSvc = new FastApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FastApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FastApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FastApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The LocationInner model constructor.
     * @property {module:model/LocationInner}
     */
    LocationInner,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The AccountApi service constructor.
    * @property {module:api/AccountApi}
    */
    AccountApi,

    /**
    * The AllApi service constructor.
    * @property {module:api/AllApi}
    */
    AllApi,

    /**
    * The ArtikalApi service constructor.
    * @property {module:api/ArtikalApi}
    */
    ArtikalApi,

    /**
    * The ArtikalCenaApi service constructor.
    * @property {module:api/ArtikalCenaApi}
    */
    ArtikalCenaApi,

    /**
    * The ArtikalRacunApi service constructor.
    * @property {module:api/ArtikalRacunApi}
    */
    ArtikalRacunApi,

    /**
    * The BackupApi service constructor.
    * @property {module:api/BackupApi}
    */
    BackupApi,

    /**
    * The FirmaApi service constructor.
    * @property {module:api/FirmaApi}
    */
    FirmaApi,

    /**
    * The ProdavnicaApi service constructor.
    * @property {module:api/ProdavnicaApi}
    */
    ProdavnicaApi,

    /**
    * The RacunApi service constructor.
    * @property {module:api/RacunApi}
    */
    RacunApi
};
