/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';

/**
* ArtikalCena service.
* @module api/ArtikalCenaApi
* @version 0.1.0
*/
export default class ArtikalCenaApi {

    /**
    * Constructs a new ArtikalCenaApi. 
    * @alias module:api/ArtikalCenaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getArtikalCenaAllArtikalCenaAllGet operation.
     * @callback module:api/ArtikalCenaApi~getArtikalCenaAllArtikalCenaAllGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artikal Cena All
     * @param {module:api/ArtikalCenaApi~getArtikalCenaAllArtikalCenaAllGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getArtikalCenaAllArtikalCenaAllGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/artikal_cena/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtikalCenaByArtikalIdArtikalCenaArtikalIdArtikalIdGet operation.
     * @callback module:api/ArtikalCenaApi~getArtikalCenaByArtikalIdArtikalCenaArtikalIdArtikalIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artikal Cena By Artikal Id
     * @param {Number} artikalId 
     * @param {module:api/ArtikalCenaApi~getArtikalCenaByArtikalIdArtikalCenaArtikalIdArtikalIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getArtikalCenaByArtikalIdArtikalCenaArtikalIdArtikalIdGet(artikalId, callback) {
      let postBody = null;
      // verify the required parameter 'artikalId' is set
      if (artikalId === undefined || artikalId === null) {
        throw new Error("Missing the required parameter 'artikalId' when calling getArtikalCenaByArtikalIdArtikalCenaArtikalIdArtikalIdGet");
      }

      let pathParams = {
        'artikal_id': artikalId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/artikal_cena/artikal_id/{artikal_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtikalCenaByIdArtikalCenaIdIdGet operation.
     * @callback module:api/ArtikalCenaApi~getArtikalCenaByIdArtikalCenaIdIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artikal Cena By Id
     * @param {Number} id 
     * @param {module:api/ArtikalCenaApi~getArtikalCenaByIdArtikalCenaIdIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getArtikalCenaByIdArtikalCenaIdIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getArtikalCenaByIdArtikalCenaIdIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/artikal_cena/id/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
