/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';

/**
* ArtikalRacun service.
* @module api/ArtikalRacunApi
* @version 0.1.0
*/
export default class ArtikalRacunApi {

    /**
    * Constructs a new ArtikalRacunApi. 
    * @alias module:api/ArtikalRacunApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getArtikalRacunByArtikalIdArtikalRacunArtikalIdIdArtiklaGet operation.
     * @callback module:api/ArtikalRacunApi~getArtikalRacunByArtikalIdArtikalRacunArtikalIdIdArtiklaGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artikal Racun By Artikal Id
     * @param {Number} idArtikla 
     * @param {module:api/ArtikalRacunApi~getArtikalRacunByArtikalIdArtikalRacunArtikalIdIdArtiklaGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getArtikalRacunByArtikalIdArtikalRacunArtikalIdIdArtiklaGet(idArtikla, callback) {
      let postBody = null;
      // verify the required parameter 'idArtikla' is set
      if (idArtikla === undefined || idArtikla === null) {
        throw new Error("Missing the required parameter 'idArtikla' when calling getArtikalRacunByArtikalIdArtikalRacunArtikalIdIdArtiklaGet");
      }

      let pathParams = {
        'id_artikla': idArtikla
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/artikal_racun/artikal_id/{id_artikla}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtikalRacunByIdArtikalRacunIdIdGet operation.
     * @callback module:api/ArtikalRacunApi~getArtikalRacunByIdArtikalRacunIdIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artikal Racun By Id
     * @param {Number} id 
     * @param {module:api/ArtikalRacunApi~getArtikalRacunByIdArtikalRacunIdIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getArtikalRacunByIdArtikalRacunIdIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getArtikalRacunByIdArtikalRacunIdIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/artikal_racun/id/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getArtikalRacunByRacunIdArtikalRacunRacunIdRacunIdGet operation.
     * @callback module:api/ArtikalRacunApi~getArtikalRacunByRacunIdArtikalRacunRacunIdRacunIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Artikal Racun By Racun Id
     * @param {Number} racunId 
     * @param {module:api/ArtikalRacunApi~getArtikalRacunByRacunIdArtikalRacunRacunIdRacunIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getArtikalRacunByRacunIdArtikalRacunRacunIdRacunIdGet(racunId, callback) {
      let postBody = null;
      // verify the required parameter 'racunId' is set
      if (racunId === undefined || racunId === null) {
        throw new Error("Missing the required parameter 'racunId' when calling getArtikalRacunByRacunIdArtikalRacunRacunIdRacunIdGet");
      }

      let pathParams = {
        'racun_id': racunId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['OAuth2PasswordBearer'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/artikal_racun/racun_id/{racun_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
