/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';

/**
* Prodavnica service.
* @module api/ProdavnicaApi
* @version 0.1.0
*/
export default class ProdavnicaApi {

    /**
    * Constructs a new ProdavnicaApi. 
    * @alias module:api/ProdavnicaApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getProdavnicaByIdProdavnicaIdIdGet operation.
     * @callback module:api/ProdavnicaApi~getProdavnicaByIdProdavnicaIdIdGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Prodavnica By Id
     * @param {Number} id 
     * @param {module:api/ProdavnicaApi~getProdavnicaByIdProdavnicaIdIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getProdavnicaByIdProdavnicaIdIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getProdavnicaByIdProdavnicaIdIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/prodavnica/id/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getProdavnicaByPibProdavnicaAllGet operation.
     * @callback module:api/ProdavnicaApi~getProdavnicaByPibProdavnicaAllGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Prodavnica By Pib
     * @param {module:api/ProdavnicaApi~getProdavnicaByPibProdavnicaAllGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getProdavnicaByPibProdavnicaAllGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/prodavnica/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getProdavnicaByPibProdavnicaPibPibGet operation.
     * @callback module:api/ProdavnicaApi~getProdavnicaByPibProdavnicaPibPibGetCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Prodavnica By Pib
     * @param {Number} pib 
     * @param {module:api/ProdavnicaApi~getProdavnicaByPibProdavnicaPibPibGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    getProdavnicaByPibProdavnicaPibPibGet(pib, callback) {
      let postBody = null;
      // verify the required parameter 'pib' is set
      if (pib === undefined || pib === null) {
        throw new Error("Missing the required parameter 'pib' when calling getProdavnicaByPibProdavnicaPibPibGet");
      }

      let pathParams = {
        'pib': pib
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/prodavnica/pib/{pib}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
